[package]
name = "pepl-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PEPL parser: token stream to AST"

[dependencies]
pepl-types = { path = "../pepl-types" }
pepl-lexer = { path = "../pepl-lexer" }
thiserror.workspace = true
